### ISSUE TITLE
Melhorar parser

### ISSUE THREAD

**Issue by fnk0c** [caioluders/DTW-D0rk-Th3-W0rld#2]

**Comment by fnk0c** [comment]
Publiquei sem querer.

Enfim, uma sugestão é você utilizar o mechanize e o beautifulsoup para realizar um scrapy na pagina do google e obter mais resultados. Caso eu nao tenha sido claro, nao exite em perguntar.

**Comment by caioluders** [comment]
O Google bloqueia bastante os parsers e tá sempre mudando , é meio difícil de acompanhar . Já vi algumas pesquisas em cima de parsear o Google , se tiver tempo eu implemento . Valeu (:
